# Generated by Django 5.1.7 on 2025-05-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
